kernel.spec: Add openssl-devel as BuildRequires
Newer kernels, e.g.: 4.15-rc8, break with the following error:

    scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory
     #include <openssl/bio.h>
                         ^

This patch fixes it by adding openssl-devel as BuildRequires, so the
openssl/bio.h header file will be available at build time.