Update to qemu 2.10.0
Update qemu.yaml to version 2.10.0 from hostos-release branch and update qemu.spec
to solve the following packaging issues due to the update:

    error: Installed (but unpackaged) file(s) found:
       /usr/share/qemu/qemu_vga.ndrv
       /usr/share/qemu/s390-netboot.img
        File listed twice: /etc/qemu
        File listed twice: /etc/qemu/bridge.conf
        Installed (but unpackaged) file(s) found:
       /usr/share/qemu/qemu_vga.ndrv
       /usr/share/qemu/s390-netboot.img

(cherry picked from commit e39aab9a87f862ffbbeb980f815b77b14527f355)