Revert "Build from release pipeline on 2017-11-17"
This reverts commit 9b1d6cfff716d8e2089356a54721992accba5061.

Paul Mackerras did a non-fast-forward push to set hostos-release branch of
http://github.com/open-power-host-os/linux.git back to 3.0-2017-09-22 tag after
having previously pushed out a merge with 4.13.13.

This revert is necessary to make Release Pipeline work again, which was failing
with the following message:

```
Command update-versions failed.
Traceback (most recent call last):
  File "host_os.py", line 79, in <module>
    SUBCOMMANDS[subcommand].run(CONF)
  File "/home/jenkins-slave/workspace/release/builds/lib/subcommands/update_versions.py", line 228, in run
    updates_available = (pkg_version.update(updater_name, updater_email)
  File "/home/jenkins-slave/workspace/release/builds/lib/subcommands/update_versions.py", line 107, in update
    (previous_version, self._repo_version))
PackageError: Current version (4.13.13) is greater than repo version (4.13.0)
```